Erp\Bundle\DocumentBundle\Entity\BillingNoteDetailStatusChanged:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\BillingNoteDetailRepository
  table: document_billingnotedetailstatuschanged
  inheritanceType: JOINED
  manyToOne:
    billingNoteDetail:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\BillingNoteDetail
      joinColumn:
        name: id_document_incomedetail
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
  fields:
    removed:
      type: boolean
      nullable: false
