Erp\Bundle\DocumentBundle\Entity\BillingNoteDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\DeliveryNoteDetailRepository
  table: document_billingnotedetail
  inheritanceType: JOINED
