Erp\Bundle\DocumentBundle\Entity\BillingNote:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\BillingNoteRepository
  table: document_billingnote
  inheritanceType: JOINED
  fields:
    bankCheck:
      type: boolean
      nullable: false
    transferMoney:
      type: simple_array
      nullable: true
    other:
      type: boolean
      nullable: false
