Erp\Bundle\DocumentBundle\Entity\DeliveryNoteDetailStatusChanged:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\DeliveryNoteDetailRepository
  table: document_deliverynotedetailstatuschanged
  inheritanceType: JOINED
  manyToOne:
    deliveryNoteDetail:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\DeliveryNoteDetail
      joinColumn:
        name: id_document_incomedetail
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
  fields:
    removed:
      type: boolean
      nullable: false
