Erp\Bundle\DocumentBundle\Entity\DocumentObjectValue:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\DocumentObjectValueRepository
  table: document_documentobjectvalue
  inheritanceType: JOINED
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY
