Erp\Bundle\DocumentBundle\Entity\ExpenseDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseOrderExpenseDetailRepository
  table: document_expensedetail
  inheritanceType: JOINED
  oneToOne:
    statusChanged:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrderExpenseDetailStatusChanged
      cascade: ["persist", "refresh"]
      joinColumn:
        name: id_document_purchaseorderexpensedetailstatuschanged
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
