Erp\Bundle\DocumentBundle\Entity\Expense:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\ExpenseRepository
  table: document_expense
  inheritanceType: JOINED
