Erp\Bundle\DocumentBundle\Entity\ExpenseDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseOrderExpenseDetailRepository
  table: document_expensedetail
  inheritanceType: JOINED
