Erp\Bundle\DocumentBundle\Entity\GoodsReceiptDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\GoodsReceiptDetailRepository
  table: document_goodsreceiptdetail
  inheritanceType: JOINED
