Erp\Bundle\DocumentBundle\Entity\IncomeFinance:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\IncomeFinance
  table: document_incomefinance
  inheritanceType: JOINED
  fields:
    total:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    discount:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    costItemTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    vatFactor:
      type: boolean
      nullable: false
    vatIncluded:
      type: boolean
      nullable: true
    vat:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    vatCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    excludeVat:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    tax:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    taxFactor:
      type: boolean
      nullable: false
    taxCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    payTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    retention:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    retentionFactor:
      type: boolean
      nullable: false
    retentionCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    retentionPayTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    netTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    paymentDate:
      type: datetime_immutable
      nullable: true
    remarkFinance:
      type: text
      nullable: true
    remarkOther:
      type: text
      nullable: true
