Erp\Bundle\DocumentBundle\Entity\IncomeFinancePaymentChannel:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\IncomeFinancePaymentChannelRepository
  table: document_incomefinancepaymentchannel
  inheritanceType: JOINED
  fields:
    paymentChannel:
      type: string
      length: 255
      nullable: true
