Erp\Bundle\DocumentBundle\Entity\PurchaseRequestDetailStatusChanged:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseRequestDetailRepository
  table: document_purchaserequestdetailstatuschanged
  inheritanceType: JOINED
  manyToOne:
    purchaseRequestDetail:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseRequestDetail
      joinColumn:
        name: id_document_purchasedetail
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
  fields:
    removed:
      type: boolean
      nullable: false
