Erp\Bundle\DocumentBundle\Entity\PurchaseRequest:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseRequestRepository
  table: document_purchaserequest
  inheritanceType: JOINED
