Erp\Bundle\DocumentBundle\Entity\PurchaseOrderExpenseDetailStatusChanged:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseOrderExpenseDetailRepository
  table: document_purchaseorderexpensedetailstatuschanged
  inheritanceType: JOINED
  manyToOne:
    purchaseOrderDetail:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrderDetail
      joinColumn:
        name: id_document_purchasedetail
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
  fields:
    removed:
      type: boolean
      nullable: false
