Erp\Bundle\DocumentBundle\Entity\PurchaseOrder:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseOrderRepository
  table: document_purchaseorder
  inheritanceType: JOINED
#  associationOverride:
#    updateOf:
#      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrder
#    updatedBys:
#      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrder
#    details:
#      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrderDetail
  fields:
    discount:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    costItemTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: false
    vatFactor:
      type: boolean
      nullable: false
    vatIncluded:
      type: boolean
      nullable: true
    vat:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    vatCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    excludeVat:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    docTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    tax:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    taxFactor:
      type: boolean
      nullable: false
    taxCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    payTotal:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    productWarranty:
      type: boolean
      nullable: true
    productWarrantyCost:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    payMethod:
      type: boolean
      nullable: true
    creditDay:
      type: integer
      nullable: true
    dueDate:
      type: datetime_immutable
      nullable: true
    payTerm:
      type: boolean
      nullable: true
    payDeposit:
      type: decimal
      precision: 15
      scale: 2
      nullable: true
    remarkFinance:
      type: text
      nullable: true
