Erp\Bundle\DocumentBundle\Entity\PurchaseOrder:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseOrderRepository
  table: document_purchaseorder
  inheritanceType: JOINED
