Erp\Bundle\DocumentBundle\Entity\PurchaseOrderDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseRequestDetailRepository
  table: document_purchaseorderdetail
  inheritanceType: JOINED
