Erp\Bundle\DocumentBundle\Entity\PurchaseOrderDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseRequestDetailRepository
  table: document_purchaseorderdetail
  inheritanceType: JOINED
  associationOverride:
    purchase:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrder
    costItem:
      cascade: ["persist", "refresh"]
  oneToOne:
    statusChanged:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseRequestDetailStatusChanged
      cascade: ["persist", "refresh"]
      joinColumn:
        name: id_document_purchaserequestdetailstatuschanged
        nullable: true
        onDelete: RESTRICT
      fetch: EAGER
