Erp\Bundle\DocumentBundle\Entity\PurchaseRequestDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\PurchaseRequestDetailRepository
  table: document_purchaserequestdetail
  inheritanceType: JOINED
  # associationOverride:
  #   purchase:
  #     targetEntity: Erp\Bundle\DocumentBundle\Entity\PurchaseRequest
  fields:
    name:
      type: string
      length: 255
      nullable: false
    unit:
      type: string
      length: 255
      nullable: false
