Erp\Bundle\DocumentBundle\Entity\Quotation:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\QuotationRepository
    table: document_quotation
    inheritanceType: JOINED
      associationOverride:
        updateOf:
          targetEntity: Erp\Bundle\DocumentBundle\Entity\Quotation
        updatedBys:
          targetEntity: Erp\Bundle\DocumentBundle\Entity\Quotation
        details:
          targetEntity: Erp\Bundle\DocumentBundle\Entity\QuotationDetail
      fields:
        discount:
          type: decimal
          precision: 15
          scale: 2
          nullable: false
        costItemTotal:
          type: decimal
          precision: 15
          scale: 2
          nullable: false
        vatFactor:
          type: boolean
          nullable: false
        vatIncluded:
          type: boolean
          nullable: true
        vat:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        vatCost:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        excludeVat:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        docTotal:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        tax:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        taxFactor:
          type: boolean
          nullable: false
        taxCost:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        payTotal:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        productWarranty:
          type: boolean
          nullable: true
        productWarrantyCost:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        payMethod:
          type: boolean
          nullable: true
        creditDay:
          type: integer
          nullable: true
        dueDate:
          type: datetime_immutable
          nullable: true
        payTerm:
          type: boolean
          nullable: true
        payDeposit:
          type: decimal
          precision: 15
          scale: 2
          nullable: true
        remarkFinance:
          type: text
          nullable: true
        conditionsOfRequestPrice:
          type: text
          nullable: true
        conditions:
          type: text
          nullable: true
