Erp\Bundle\DocumentBundle\Entity\QuotationDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\QuotationDetailRepository
  table: document_quotationdetail
  inheritanceType: JOINED
