Erp\Bundle\DocumentBundle\Entity\Quotation:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\QuotationRepository
  table: document_quotation
  inheritanceType: JOINED
