Erp\Bundle\DocumentBundle\Entity\RequestForQuotation:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\RequestForQuotationRepository
  table: document_requestforquotation
  inheritanceType: JOINED
  manyToMany:
    requestedVendors:
      targetEntity: Erp\Bundle\MasterBundle\Entity\Vendor
      joinTable:
        name: document_requestforquotation_vendor
        joinColumns:
          joinColumn:
            name: id_document_requestforquotation
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          joinColumn:
            name: id_master_vendor
            nullable: false
            onDelete: RESTRICT
  manyToOne:
    project:
      targetEntity: Erp\Bundle\MasterBundle\Entity\Project
      joinColumn:
        name: id_master_project
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
    requester:
      targetEntity: Erp\Bundle\MasterBundle\Entity\Employee
      joinColumn:
        name: id_master_employee
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
    boq:
      targetEntity: Erp\Bundle\MasterBundle\Entity\ProjectBoqData
      joinColumn:
        name: id_master_projectboqdata
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
    budgetType:
      targetEntity: Erp\Bundle\MasterBundle\Entity\ProjectBoqBudgetType
      joinColumn:
        name: id_master_projectboqbudgettype
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
  oneToMany:
    details:
      targetEntity: Erp\Bundle\DocumentBundle\Entity\RequestForQuotationDetail
      cascade: ["persist", "refresh"]
      mappedBy: requestForQuotation
  fields:
    vendorContactInformation:
      type: string
      length: 255
      nullable: true
    vendorAddress:
      type: text
      nullable: true
    contactInformation:
      type: string
      length: 255
      nullable: false
    wantedDate:
      type: date_immutable
      nullable: false
    deliveryDate:
      type: datetime_immutable
      nullable: true