Erp\Bundle\DocumentBundle\Entity\RequestForQuotation:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\RequestForQuotationRepository
  table: document_requestforquotation
  inheritanceType: JOINED
  manyToMany:
    requestedVendors:
      targetEntity: Erp\Bundle\MasterBundle\Entity\Vendor
      joinTable:
        name: document_requestforquotation_vendor
        joinColumns:
          joinColumn:
            name: id_document_requestforquotation
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          joinColumn:
            name: id_master_vendor
            nullable: false
            onDelete: RESTRICT
  fields:
    dueDate:
      type: datetime_immutable
      nullable: true
