Erp\Bundle\DocumentBundle\Entity\Revenue:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\RevenueRepository
  table: document_revenue
  inheritanceType: JOINED
