Erp\Bundle\DocumentBundle\Entity\RevenueDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\TaxInvoiceDetailRepository
  table: document_revenuedetail
  inheritanceType: JOINED
