Erp\Bundle\DocumentBundle\Entity\TaxInvoice:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\TaxInvoiceRepository
  table: document_taxinvoice
  inheritanceType: JOINED
