Erp\Bundle\DocumentBundle\Entity\TaxInvoiceDetail:
  type: entity
  #repositoryClass: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Repository\BillingNoteDetailRepository
  table: document_taxinvoicedetail
  inheritanceType: JOINED
