parameters:
    container.autowiring.strict_mode: true

services:

  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  #Erp\Bundle\CoreBundle\Domain\CQRS\SimpleCommandHandler: "@erp_master.service.command.simple_handler"

  Erp\Bundle\DocumentBundle\:
    resource: '../../*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../{Collection,Entity,Infrastructure/ORM/Repository}'

  # MUST call setContainer when using jms/di-extra-bundle
  # BUG: https://github.com/symfony/symfony/issues/23200
  Erp\Bundle\DocumentBundle\Controller\:
    resource: '../../Controller'
    exclude: '../../Controller/PurchaseOrderQuantitySummaryApiQueyController.php'
    tags: ['controller.service_arguments']
#    calls:
#      - [setContainer, ["@service_container"]]

  Erp\Bundle\DocumentBundle\Controller\PurchaseOrderQuantitySummaryApiQueyController:
    tags: ['controller.service_arguments']

  #Service
  Erp\Bundle\DocumentBundle\Service\PDFService:
    #class: Erp\Bundle\DocumentBundle\Service\PDFService
    arguments:
      -
        tempDir: "%kernel.cache_dir%"
        fontDir: ["@=service('file_locator').locate('@ErpDocumentBundle/Resources/fonts')"]
        fontdata:
          thsarabun:
            R: 'THSarabun.ttf'
            B: 'THSarabun Bold.ttf'
            I: 'THSarabun Italic.ttf'
            BI: 'THSarabun Bold Italic.ttf'
    public: true

  # --------------- domain service
  # domain service
  Erp\Bundle\DocumentBundle\Domain\CQRS\DocumentQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\DocumentQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\PurchaseQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\PurchaseQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\PurchaseRequestQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\PurchaseRequestQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\PurchaseOrderQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\PurchaseOrderQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\ProjectBoqSummaryQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\ProjectBoqSummaryQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\QuotationQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\QuotationQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\GoodsReceiptQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\GoodsReceiptQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\PurchaseOrderQuantitySummaryQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\PurchaseOrderQuantitySummaryQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\IncomeQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\IncomeQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\DeliveryNoteQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\DeliveryNoteQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\BillingNoteQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\BillingNoteQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\ExpenseQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\ExpenseQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\TaxInvoiceQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\TaxInvoiceQueryService'
  Erp\Bundle\DocumentBundle\Domain\CQRS\RevenueQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Service\RevenueQueryService'

  Erp\Bundle\DocumentBundle\Domain\CQRS\Query\DocumentQuery: '@Erp\Bundle\DocumentBundle\Infrastructure\ORM\Query\DocumentQuery'

  #Entity Listerner
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\TerminatedDocumentListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\TerminatedDocumentListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\TerminatedDocument, event: preFlush }

  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\PurchaseRequestListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\PurchaseRequestListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\PurchaseRequest, event: preFlush }

  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\PurchaseOrderListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\PurchaseOrderListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\PurchaseOrder, event: preFlush }
      
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\RequestForQuotationListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\RequestForQuotationListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\RequestForQuotation, event: preFlush }
      
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\QuotationListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\QuotationListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\Quotation, event: preFlush }
      
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\GoodsReceiptListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\GoodsReceiptListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\GoodsReceipt, event: preFlush }

  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\DeliveryNoteListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\DeliveryNoteListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\DeliveryNote, event: preFlush }
      
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\BillingNoteListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\BillingNoteListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\BillingNote, event: preFlush }

  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\ExpenseListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\ExpenseListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\Expense, event: preFlush }
      
  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\TaxInvoiceListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\TaxInvoiceListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\TaxInvoice, event: preFlush }

  Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\RevenueListener:
    #class: Erp\Bundle\DocumentBundle\Infrastructure\ORM\Listener\RevenueListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\DocumentBundle\Entity\Revenue, event: preFlush }
