Erp\Bundle\DocumentBundle\Entity\DeliveryNote:
  access_type: property
  properties:
    updateOf:
      type: Erp\Bundle\DocumentBundle\Entity\DeliveryNote
    updatedBy:
      type: Erp\Bundle\DocumentBundle\Entity\DeliveryNote
    details:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\DeliveryNoteDetail>
