Erp\Bundle\DocumentBundle\Entity\RequestForQuotation:
  access_type: property
  properties:
    updateOf:
      type: Erp\Bundle\DocumentBundle\Entity\RequestForQuotation
    updatedBy:
      type: Erp\Bundle\DocumentBundle\Entity\RequestForQuotation
    details:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\RequestForQuotationDetail>
    requestForQuotationVendors:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\RequestForQuotationVendor>
    requestedVendors:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\MasterBundle\Entity\Vendor>
    project:
      type: Erp\Bundle\MasterBundle\Entity\Project
    vendor:
      type: Erp\Bundle\MasterBundle\Entity\Vendor
    requester:
      type: Erp\Bundle\MasterBundle\Entity\Employee
    wantedDate:
      type: DateTimeImmutable
    deliveryDate:
      type: DateTimeImmutable
