Erp\Bundle\DocumentBundle\Entity\BillingNote:
  access_type: property
  properties:
    updateOf:
      type: Erp\Bundle\DocumentBundle\Entity\BillingNote
    updatedBy:
      type: Erp\Bundle\DocumentBundle\Entity\BillingNote
    details:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\BillingNoteDetail>
    transferMoney:
      type: array<string>
