Erp\Bundle\DocumentBundle\Entity\BillingNoteDetail:
  access_type: property
  properties:
    income:
      type: Erp\Bundle\DocumentBundle\Entity\BillingNote
    statusChanged:
      type: Erp\Bundle\DocumentBundle\Entity\DeliveryNoteDetailStatusChanged
      