Erp\Bundle\DocumentBundle\Entity\Income:
  access_type: property
  properties:
    details:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\IncomeDetail>
    project:
      type: Erp\Bundle\MasterBundle\Entity\Project
      groups: [short]
    requester:
      type: Erp\Bundle\MasterBundle\Entity\Employee
      groups: [short]
    boq:
      type: Erp\Bundle\MasterBundle\Entity\ProjectBoq
      max_depth: 1
    deliveryDate:
      type: DateTimeImmutable
      groups: [short]
