Erp\Bundle\DocumentBundle\Entity\PurchaseOrderDetail:
  access_type: property
  properties:
    purchase:
      type: Erp\Bundle\DocumentBundle\Entity\PurchaseOrder
    statusChanged:
      type: Erp\Bundle\DocumentBundle\Entity\PurchaseRequestDetailStatusChanged
