Erp\Bundle\DocumentBundle\Entity\Expense:
  access_type: property
  properties:
    updateOf:
      type: Erp\Bundle\DocumentBundle\Entity\Expense
    updatedBy:
      type: Erp\Bundle\DocumentBundle\Entity\Expense
    details:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\DocumentBundle\Entity\ExpenseDetail>
    dueDate:
      type: DateTimeImmutable
